name: g_lens_generator
description: A package for generating lens classes in GHTK.
version: 1.0.0

environment:
  sdk: '>=2.13.0 <4.0.0'


dependencies:
  analyzer: '>=2.0.0 <=6.4.1'
  build: ^2.0.1
  collection: ^1.15.0
  functional_data: ^1.1.1
  source_gen: ^1.2.7
  yaml: ^3.1.2

dev_dependencies:
  build_resolvers: ^2.0.2
  build_runner: ^2.2.0

dependency_overrides:
  g_lens:
    path: ../g_lens
